name: Hyvä Admin PHP7.3 Backportability Test
on: [ push, pull_request ]

jobs:
    php73-backport-tests:
        name: PHP73 Backportability
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
            es:
                image: docker.io/wardenenv/elasticsearch:7.8
                ports:
                    - 9200:9200
                env:
                    'discovery.type': single-node
                    'xpack.security.enabled': false
                    ES_JAVA_OPTS: "-Xms64m -Xmx512m"
                options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            -   uses: actions/checkout@v2
            -   name: Backport and test
                uses: extdn/github-actions-m2/magento-integration-tests/7.3@master
                with:
                    module_name: Hyva_Admin
                    composer_name: hyva-themes/module-magento2-admin
                    ce_version: '2.4.1'
                    magento_post_install_script: vendor/hyva-themes/module-magento2-admin/build/backport-and-unit-test.sh
